name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://oliver.ni/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build site
        run: nix build .#for-production

      - name: Deploy
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avPh --delete --exclude=.htaccess
          path: result/
          remote_path: ~/public_html/oliver.ni
          remote_host: tsunami.ocf.berkeley.edu
          remote_user: oliverni
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
